# Automatically generated by Qwiklabs
variable "gcp_project_id" {
  type        = string
  description = "The GCP project ID to apply this config to"
}

variable "gcp_region" {
  type        = string
  description = "Region of the new GKE cluster"
  default     = "us-central1"
}

variable "gcp_zone" {
  description = "The GCP zone. Used for VM and GKE cluster"
  type        = string
  default     = "us-central1-a"
}

variable "service_account_key_file" {
    type = string
    description = "key file location"
}

# Using default network for simplicity
variable "gcp_network" {
  type        = string
  description = "The name of the VPC network to host the GKE cluster"
  default     = "default"
}

# Variables for this workshop
variable "gcp_cluster_name" {
  type        = string
  description = "Name given to the new GKE cluster"
  default     = "online-boutique"
}

variable "gcp_artifact_name" {
  type        = string
  description = "Name given to the new Artifact Registry"
  default     = "boutique"
}

variable "namespace" {
  type        = string
  description = "Kubernetes Namespace in which the Online Boutique resources are to be deployed"
  default     = "default"
}

variable "filepath_manifest" {
  type        = string
  description = "Path to Online Boutique's Kubernetes resources, written using Kustomize"
  default     = "kustomize/"
}

variable "gcp_service_list" {
  description = "The list of apis necessary for the project"
  type        = list(string)
  default = [
    "container.googleapis.com",
    "storage.googleapis.com",
    "servicenetworking.googleapis.com",
    "cloudbuild.googleapis.com",
    "containerregistry.googleapis.com",
    "artifactregistry.googleapis.com",
    "monitoring.googleapis.com",
    "cloudtrace.googleapis.com",
    "cloudprofiler.googleapis.com"
  ]
}

# Variables from original lab - not currently used 
variable "userName" {
  description = "The username for the lab. Note: This variable is declared to avoid errors but is not currently used in the configuration."
  type        = string
  default     = "username"
}

variable "userPassword" {
  description = "The password for the lab. Note: This variable is declared to avoid errors but is not currently used in the configuration."
  type        = string
  default     = "password"
}
