apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: llm
        image: us-central1-docker.pkg.dev/arm-evangelism-dev/llm-cpu-env/arm:latest
        command: ["/bin/sh", "-c"]
        args: [
          "llm serve /root/.cache/huggingface/models--google--gemma-3-270m/snapshots/9b0cfec892e2bc2afd938c98eabe4e4a7b1e0ca1 --dtype=bfloat16 --disable-sliding-window"
        ]
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "15"
            memory: "60Gi"
        env:
        - name: HF_HUB_OFFLINE
          value: "1"
        - name: llm_USE_V1
          value: "1"
        - name: llm_CPU_KVCACHE_SPACE
          value: "40"
        - name: llm_CPU_NUM_OF_RESERVED_CPU
          value: "1"
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: model-storage
            mountPath: /root/.cache/huggingface
        securityContext:
          seccompProfile:
            type: Unconfined
          capabilities:
            add:
            - SYS_NICE
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: llm-models
---
apiVersion: v1
kind: Service
metadata:
  name: llm-server
spec:
  selector:
    app.kubernetes.io/name: llm
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP