apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: llm
        image: us-central1-docker.pkg.dev/arm-evangelism-dev/llm-cpu-env/arm:latest
        command: ["/bin/sh", "-c"]
        args: [
          "llama-server -m ~/models/model.gguf --port 8080"
        ]
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "15"
            memory: "60Gi"
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: model-storage
            mountPath: /models
        securityContext:
          seccompProfile:
            type: Unconfined
          capabilities:
            add:
            - SYS_NICE
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: llm-models
---
apiVersion: v1
kind: Service
metadata:
  name: llm-server
spec:
  selector:
    app.kubernetes.io/name: llm
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP