apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- shoppingassistantservice.yaml
patches:
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENABLE_ASSISTANT
        value: "true"
